apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nessus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/freddo256/nessus-kubernetes.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: nessus
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true