---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nessus
  namespace: argocd
spec:
  project: default
  source:
    chart: nessus
    repoURL: https://freddo256.github.io/nessus-kubernetes-argocd/helm/charts
    targetRevision: "0.1.0"
    path: .
    helm:
      releaseName: nessus
      values: |
        service:
          type: LoadBalancer
          port: 443
        image:
          tag: latest
          imagePullPolicy: IfNotPresent
        nessus:
          activation_code: ""
          username: ""
          password: ""
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nessus
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true