---
apiVersion: v1
kind: Service
metadata:
  name: nessus-service
  namespace: nessus
spec:
  selector:
    app: nessus
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8834