---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessus-deployment
  namespace: nessus
  labels:
    app: nessus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nessus
  template:
    metadata:
      labels:
        app: nessus
    spec:
      containers:
      - name: nessus
        image: tenableofficial/nessus:latest
        args:
          - "-e ACTIVATION_CODE=PG6G-RCJJ-4SP4-EQDQ-EWCX"
          - "-e USERNAME=admin"
          - "-e PASSWORD=admin"
        ports:
        - containerPort: 8834
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1000m"
            memory: "1000m"