service:
  type: LoadBalancer
  port: 443

image:
  tag: latest

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

args:
- "-e ACTIVATION_CODE="
- "-e USERNAME="
- "-e PASSWORD="

nessus:
  activation_code: ""
  username: ""
  password: ""